//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudManage1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class eduDetail
    {
        public int sid { get; set; }
        public Nullable<int> id { get; set; }
        [Required(ErrorMessage = "please enter your 10th percentage")]
        public string ten_percent { get; set; }
        [Required(ErrorMessage = "please choose your 10th year of passing")]
        public Nullable<int> ten_yop { get; set; }
        [Required(ErrorMessage = "please choose your 10th Institute")]
        public string ten_inst { get; set; }
        [Required(ErrorMessage = "please enter your 12th percentage")]
        public string twel_percent { get; set; }
        [Required(ErrorMessage = "please choose your 12th year of passing")]
        public Nullable<int> twel_yop { get; set; }
        [Required(ErrorMessage = "please choose your 12th Institute")]
        public string twel_inst { get; set; }
        [Required(ErrorMessage = "please enter your current CGPA.If you are in first semester enter 0")]
        public string curr_CGPA { get; set; }
        [Required(ErrorMessage = "please choose your Current sem")]
        public Nullable<int> curr_sem { get; set; }

        public virtual stuDetail stuDetail { get; set; }

    }
}
